const ADD_TO_LİST = "ADD_TO_LİST";
const REMOVE_TO_LİST = "REMOVE_TO_LİST";
const FETCH_TASKS = "FETCH_TO_TASKS";
const DARKMODE = "DARKMODE";
const WHİTEMODE =  "WHİTEMODE";
export {ADD_TO_LİST,REMOVE_TO_LİST,FETCH_TASKS,DARKMODE,WHİTEMODE,}
